# GitHub Pages Configuration
title: Physics Projects Portfolio
description: Advanced computational physics projects from MIT Data Science for Physics course
author: Tenzin Jampa
email: your-email@example.com

# Site settings
url: "https://[your-username].github.io"
baseurl: "/physics_projects"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Plugins (if needed)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - .gitignore
  - node_modules
  - vendor 